/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=5f1444eb&sid=78b32519
 */
import * as React from "react";
import { CreditCardProps } from "./types";

export const CreditCard: React.FC<CreditCardProps> = ({
  cardNumber,
  name,
  expiry,
  logoUrl,
  chipUrl,
}) => {
  return (
    <article className="flex z-10 flex-col items-start px-11 py-9 max-w-full bg-white bg-opacity-10 rounded-[35px] w-[421px] max-md:px-5">
      <div className="flex gap-5 justify-between self-stretch">
        <img
          loading="lazy"
          src={logoUrl}
          alt="Credit card logo"
          className="object-contain shrink-0 self-start aspect-[1.65] w-[43px]"
        />
        <img
          loading="lazy"
          src={chipUrl}
          alt="Credit card chip"
          className="object-contain shrink-0 aspect-[0.74] w-[25px]"
        />
      </div>
      <div className="mt-7 text-base font-semibold text-gray-200">
        Credit Card No.
      </div>
      <div className="mt-2.5 text-2xl font-bold leading-tight text-white">
        {cardNumber}
      </div>
      <div className="flex gap-8 mt-6">
        <div className="flex flex-col self-start mt-1">
          <div className="self-start text-base font-semibold text-gray-200">
            Name
          </div>
          <div className="mt-1.5 text-sm font-medium text-white">{name}</div>
        </div>
        <div className="flex flex-col font-semibold whitespace-nowrap">
          <div className="self-start text-base text-gray-200">Exp.</div>
          <div className="mt-2.5 text-sm text-white">{expiry}</div>
        </div>
      </div>
    </article>
  );
};
