/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=5f1444eb&sid=78b32519
 */
export interface CreditCardProps {
  cardNumber: string;
  name: string;
  expiry: string;
  logoUrl: string;
  chipUrl: string;
}
