/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=7df1e7ba&sid=d3e3c927
 */
type LogoItem = {
  src: string;
  alt: string;
  className: string;
};

export const logos: LogoItem[] = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/d7cf1907c5a0b20cabc960df17d5022f0d24d3d2d2ada0d29bc7c8494dc65bfa?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    alt: "Company Logo 1",
    className: "object-contain shrink-0 aspect-[3.31] w-[106px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/0b3681fae612839a17311d9439c38e0965e1b72477d686bd795682142a0c4e04?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    alt: "Company Logo 2",
    className: "object-contain shrink-0 aspect-[2.81] w-[90px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/5571126295943ff6bfb47294025b12a1bacfbae10aaff5ace7794b6945318caf?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    alt: "Company Logo 3",
    className: "object-contain shrink-0 aspect-[3.34] w-[107px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/a9a4a1ecd6da2ec14bcfa2118a75416a2d43e2509d43f2ebf8523b20e63818da?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    alt: "Company Logo 4",
    className: "object-contain shrink-0 aspect-[7.41] w-[237px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/cab9e9bcb413b7515a4f55af874570e018d13ac14344ed740821408e73e9313f?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    alt: "Company Logo 5",
    className: "object-contain shrink-0 aspect-[3.18] w-[102px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/c887dad52c6996c9873d3054bb43fde1fbe051cbb37c5504d79c0979f77909dd?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    alt: "Company Logo 6",
    className: "object-contain shrink-0 aspect-[3.15] w-[101px]",
  },
];
