/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=7df1e7ba&sid=d3e3c927
 */
import * as React from "react";
import { logos } from "./LogoData";

export const LogoSlider: React.FC = () => {
  return (
    <section
      data-layername="logoSlider"
      className="flex flex-wrap gap-10 mx-8 justify-between items-center mt-32 max-w-full w-[1240px] max-md:mt-10"
      aria-label="Partner Logos"
    >
      {logos.map((logo, index) => (
        <img
          key={index}
          loading="lazy"
          src={logo.src}
          alt={logo.alt}
          className={`transition-transform duration-200 ease-in-out ${logo.className} max-md:w-[60%] max-md:max-w-[100px] max-md:mx-auto`}
          // Adjusted width for mobile responsiveness
        />
      ))}
    </section>
  );
};
