/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=90e0aa73&sid=8bdf2d1e
 */
import * as React from "react";

interface FeatureCardProps {
  iconSrc: string;
  title: string;
  description: string;
}

export const FeatureCard: React.FC<FeatureCardProps> = ({
  iconSrc,
  title,
  description,
}) => {
  return (
    <article className="flex gap-6 items-start min-w-[240px] w-[392px]">
      <div className="flex overflow-hidden gap-2.5 items-center p-4 w-16 h-16 bg-gray-700 rounded-3xl">
        <img
          loading="lazy"
          src={iconSrc}
          alt=""
          className="object-contain w-8 aspect-square"
        />
      </div>
      <div className="flex flex-col flex-1 shrink basis-8 min-w-[240px]">
        <h3 className="text-2xl font-medium text-white">{title}</h3>
        <p className="mt-2 text-base text-zinc-400">{description}</p>
      </div>
    </article>
  );
};
