/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=90e0aa73&sid=8bdf2d1e
 */
import * as React from "react";
import { FeatureCard } from "./FeatureCard";

const featureData = [
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/9f6b2f09f0fe03c314c51b69c66628d2bb0cf606d615f5fde1236fa9fbcc50a5?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    title: "Security Guarantee",
    description: "Your data and funds will be securely protected.",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/eef63196bb787adbd69ea45c34b213a5570baa10c32f2a0791c21218b8ab1080?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    title: "Investing",
    description: "Your data and funds will be securely protected.",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/07b7d95537f8a9b179218c979eb61b5c1675f98fa32ccb64399b026b8d7c2d07?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    title: "Multiple Method",
    description: "Your data and funds will be securely protected.",
  },
];

export const Features: React.FC = () => {
  return (
    <section
      data-layername="features"
      className="flex flex-col items-center mt-32 max-md:mt-10 max-md:max-w-full"
    >
      <h2
        data-layername="whatDoWeOffer"
        className="text-4xl font-bold text-white"
      >
        What do we offer?
      </h2>
      <div className="flex flex-wrap gap-8 mx-8 items-start mt-16 max-md:mt-10 max-md:max-w-full">
        {featureData.map((feature, index) => (
          <FeatureCard
            key={index}
            iconSrc={feature.iconSrc}
            title={feature.title}
            description={feature.description}
          />
        ))}
      </div>
    </section>
  );
};
