/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=20031a50&sid=f2528903
 */
export interface FooterLinkProps {
  title: string;
  links: string[];
}

export interface LogoSectionProps {
  logoSrc: string;
  title: string;
  description: string;
}
