/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=8a6723c6&sid=cbea9fef
 */
import * as React from "react";
import { TestimonialCard } from "./TestimonialCard";

const testimonialData = [
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/a4686ffaab0fc84b3d5803196a1aa3e1ebdba4cbf7af136658154d9fb6b8e9b5?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    testimonialText:  "Financial literacy is the key to financial independence.",
    avatarSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/145f280c7c6ca41f01e7af6db96be3084e08adefcef266f49010646a6403f486?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    name: "Aruzhan Kamalbek",
    role: "UIUX Designer",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/d3e81d8b2268b4d7b480e48e76e89f94636670dbffb2629d8d3e80cdc849eb40?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    testimonialText:
      "Investments are seeds that you plant today to reap tomorrow.",
    avatarSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/7e085838577c4f4ab5cb0136aee02747e2bf5c07099e5c1b4ea770d20fc09cca?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    name: "Yerkebulan Zhaksylykov",
    role: "Web Developer",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/70b855a7e1f844012bdaee860f5d872f412db03c47435b4d1c7439d7a3ebcd73?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    testimonialText:
      "A good financial plan is a map that helps you avoid financial storms.",
    avatarSrc:
      "https://cdn.builder.io/api/v1/image/assets/9fef530e97fe4035b3ccf762ae2eae01/d2c9c7e8e8d0fe6a1bc2c3f86557203ff32a17dd7ec75097b0152baa83524f75?apiKey=9fef530e97fe4035b3ccf762ae2eae01&",
    name: "Elmira Zhakupova",
    role: "CEO of FinLit.AI HR, PR Manager",
  },
];

export const TestimonialSection: React.FC = () => {
  return (
    <section id="reviews" className="flex flex-wrap gap-8 justify-center items-start px-12 mt-32 max-w-full w-[1240px] max-md:mt-10">
      {testimonialData.map((testimonial, index) => (
        <TestimonialCard key={index} {...testimonial} />
      ))}
    </section>
  );
};
