/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=8a6723c6&sid=cbea9fef
 */
export interface TestimonialCardProps {
  iconSrc: string;
  testimonialText: string;
  avatarSrc: string;
  name: string;
  role: string;
}
