/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=c4640a79&sid=b0702c52
 */
import * as React from "react";

interface StatCardProps {
  value: string;
  label: string;
}

export const StatCard: React.FC<StatCardProps> = ({ value, label }) => {
  return (
    <article className="flex flex-col justify-center items-center min-w-[240px] w-[278px]">
      <h3 className="text-5xl font-bold tracking-tight leading-none text-white max-md:text-4xl">
        {value}
      </h3>
      <p className="mt-2 text-base font-medium text-green-600">{label}</p>
    </article>
  );
};
