/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=ff525ced&sid=fb7204a0
 */
export interface UserStatProps {
  count: string;
  description: string;
}

export interface ButtonProps {
  text: string;
  iconSrc: string;
}
